### ISSUE TITLE
Salvager config not working properly

### ISSUE THREAD

**Issue by ViRb3** [SilentChaos512/Silent-Gear#262]
## Versions

- **Silent Gear**: 1.16.3-2.3.5+170
- **Silent's Gems**: N/A
- **Silent Lib**: 1.16.3-4.9.0+63
- **Forge**: 35.0.18
- **Modpack**: ATM6 1.3.1
- **Optifine Installed**: N/A

## Expected Behavior
From the config:
```toml
#Settings for the salvager
[salvager]

	[salvager.partLossRate]
		#Minimum rate of part loss when salvaging items. 0 = no loss, 1 = complete loss.
		#Rate depends on remaining durability.
		#Range: 0.0 ~ 1.0
		min = 0.5
		#Maximum rate of part loss when salvaging items. 0 = no loss, 1 = complete loss.
		#Rate depends on remaining durability.
		#Range: 0.0 ~ 1.0
		max = 1.0
```
The way I understand it, with full durability I will get half of the items back. With almost no durability, I will get nothing back. In reality, the behavior seems to be mostly random. Example, courtesy of @gogedo:

Shovel = 1 Stick
Sword = 2 ingot
Boots = 2 ingot
Helmet = 1 ingot
Pickaxe = 1 ingot
Leggings = 5 ingot
Chestplate= 2 ingot
